[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.black]
line-length = 79

[tool.docc]
discovery = [
    "docc.cst.discover",
]

build = [
    "docc.cst.parse",
    "docc.cst.build",
]

transform = [
    "docc.cst.annotate",
    "docc.cst.transform",
    "docc.references.index",
    "docc.html",
]

[tool.docc.plugins."docc.cst.discover"]
paths = [
    "src",
]

[tool.docc.output]
path = "docs"
extension = ".html"
