[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.black]
line-length = 79

[tool.docc]
discovery = [
    "docc.mypy.discover",
]

build = [
    "docc.python.build",
    "docc.mypy.build",
]

transform = [
    "docc.mypy.transform",
    "docc.python.transform",
    "docc.references.index",
    "docc.html",
]

[tool.docc.plugins."docc.mypy.discover"]
paths = [
    "src",
]

[tool.docc.output]
path = "docs"
extension = ".html"
