name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        py: ["3.10", "pypy3.10", "3.x"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    name: ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Install Tox
        run: python -m pip install tox-gh>=1.3

      - name: Run Tests
        run: tox
